import { Concesionario } from './concesionario.models';

export const concesionarios: Concesionario[] = [
  {
    nombre: "Gibson, O'Hara and Gulgowski",
    ccaa: 'Sioux Falls',
    email: 'https://loremflickr.com/640/480/business',
    direccion: '82090',
    telefono: 60,
    coches: 'Camaro',
    id: '1',
  },
  {
    nombre: 'Schaden - Schowalter',
    ccaa: "Lee's Summit",
    email: 'https://loremflickr.com/640/480/business',
    direccion: '4561',
    telefono: 3,
    coches: 'Model S',
    id: '2',
  },
  {
    nombre: 'Koepp - Brown',
    ccaa: 'Pinellas Park',
    email: 'https://loremflickr.com/640/480/business',
    direccion: '57556',
    telefono: 2,
    coches: 'Land Cruiser',
    id: '3',
  },
  {
    nombre: 'Reichert, Braun and Rogahn',
    ccaa: 'Palo Alto',
    email: 'https://loremflickr.com/640/480/business',
    direccion: '01837',
    telefono: 15,
    coches: 'Golf',
    id: '4',
  },
  {
    nombre: 'Schroeder - Kilback',
    ccaa: 'Bradenton',
    email: 'https://loremflickr.com/640/480/business',
    direccion: '47979',
    telefono: 52,
    coches: 'Colorado',
    id: '5',
  },
  {
    nombre: 'Schumm LLC',
    ccaa: 'Lowell',
    email: 'https://loremflickr.com/640/480/business',
    direccion: '1408',
    telefono: 8,
    coches: 'Model Y',
    id: '6',
  },
  {
    nombre: 'Harber, Bartoletti and Marks',
    ccaa: 'Orlando',
    email: 'https://loremflickr.com/640/480/business',
    direccion: '114',
    telefono: 8,
    coches: 'Sentra',
    id: '7',
  },
  {
    nombre: 'Mohr Group',
    ccaa: 'New Britain',
    email: 'https://loremflickr.com/640/480/business',
    direccion: '8687',
    telefono: 59,
    coches: 'Volt',
    id: '8',
  },
  {
    nombre: 'Mayer - Strosin',
    ccaa: 'Birmingham',
    email: 'https://loremflickr.com/640/480/business',
    direccion: '0872',
    telefono: 29,
    coches: 'Fiesta',
    id: '9',
  },
  {
    nombre: 'Boehm and Sons',
    ccaa: 'Middletown',
    email: 'https://loremflickr.com/640/480/business',
    direccion: '61396',
    telefono: 19,
    coches: 'CX-9',
    id: '10',
  },
  {
    nombre: 'Lind, Pfeffer and Friesen',
    ccaa: 'Harlingen',
    email: 'https://loremflickr.com/640/480/business',
    direccion: '3849',
    telefono: 46,
    coches: '1',
    id: '11',
  },
  {
    nombre: 'Goyette, Heidenreich and Corwin',
    ccaa: 'Poinciana',
    email: 'https://loremflickr.com/640/480/business',
    direccion: '761',
    telefono: 57,
    coches: 'A8',
    id: '12',
  },
  {
    nombre: 'Leffler, Kutch and Mohr',
    ccaa: 'Castle Rock',
    email: 'https://loremflickr.com/640/480/business',
    direccion: '095',
    telefono: 80,
    coches: 'Camaro',
    id: '13',
  },
  {
    nombre: 'Langosh LLC',
    ccaa: 'Escondido',
    email: 'https://loremflickr.com/640/480/business',
    direccion: '57792',
    telefono: 35,
    coches: 'A8',
    id: '14',
  },
  {
    nombre: 'Davis, Anderson and Crona',
    ccaa: 'Deltona',
    email: 'https://loremflickr.com/640/480/business',
    direccion: '180',
    telefono: 10,
    coches: 'A4',
    id: '15',
  },
  {
    nombre: 'Wiza - Zulauf',
    ccaa: 'Santa Barbara',
    email: 'https://loremflickr.com/640/480/business',
    direccion: '9998',
    telefono: 28,
    coches: 'Wrangler',
    id: '16',
  },
  {
    nombre: 'Cartwright - Hackett',
    ccaa: 'Sandy',
    email: 'https://loremflickr.com/640/480/business',
    direccion: '868',
    telefono: 41,
    coches: 'Focus',
    id: '17',
  },
];
